name: CI

on:
  push:
    branches:
      - main
      - master
      - dev
      - 'v*.*'
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Initialize Cache Composer
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      # Initialize Composer
      - uses: php-actions/composer@v6
        env:
          COMPOSER: 'composer.json'
        with:
          php_version: '7.2'
          version: 1
          command: run-script
          args: post-install-cmd

      # Initialize Node
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true
          cache: npm
          cache-dependency-path: package-lock.json
      - name: 'Create folder .cache s'
        run: |
          mkdir -p .cache && cd .cache && touch .gitkeep

      - run: npm ci
      - run: npm run format-check
      - run: composer run sniff-check
