name: CI

on:
  push:
    branches:
      - main
      - master
      - dev
      - 'v*.*'
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
#   cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Initialize Cache Composer
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      # Initialize Composer
      # Use v1; v2 throws an error due to PHP v7.2 support
      # Ref: https://github.com/marketplace/actions/composer-update-action
      # - uses: php-actions/composer@v6
      #   env:
      #     COMPOSER: 'composer.json'
      #   with:
      #     php_version: '7.2'
      #     version: 1

      - run: mkdir -p .cache

      - name: Run Code Sniffer
        run: composer run sniff-check

      # Initialize Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          check-latest: true
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci
      - name: Run Format check
        run: npm run format-check
